# Submission Jupyter Notebook for Homework 1

Question 1: Pandas version (1 point)

In [22]:
import pandas as pd
import numpy as np

In [2]:
print(pd.__version__)

2.3.2

Question 2. Records count (1 point)

In [3]:
df = pd.read_csv("car_fuel_efficiency.csv")

In [4]:
df

,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,model_year,origin,fuel_type,drivetrain,num_doors,fuel_efficiency_mpg
0,170,3.0,159.0,3413.433759,17.7,2003,Europe,Gasoline,All-wheel drive,0.0,13.231729
1,130,5.0,97.0,3149.664934,17.8,2007,USA,Gasoline,Front-wheel drive,0.0,13.688217
2,170,NaN,78.0,3079.038997,15.1,2018,Europe,Gasoline,Front-wheel drive,0.0,14.246341
3,220,4.0,NaN,2542.392402,20.2,2009,USA,Diesel,All-wheel drive,2.0,16.912736
4,210,1.0,140.0,3460.870990,14.4,2009,Europe,Gasoline,All-wheel drive,2.0,12.488369
...,...,...,...,...,...,...,...,...,...,...,...
9699,140,5.0,164.0,2981.107371,17.3,2013,Europe,Diesel,Front-wheel drive,NaN,15.101802
9700,180,NaN,154.0,2439.525729,15.0,2004,USA,Gasoline,All-wheel drive,0.0,17.962326
9701,220,2.0,138.0,2583.471318,15.1,2008,USA,Diesel,All-wheel drive,-1.0,17.186587
9702,230,4.0,177.0,2905.527390,19.4,2011,USA,Diesel,Front-wheel drive,1.0,15.331551
9703,270,3.0,140.0,2908.043477,14.7,2005,Asia,Diesel,All-wheel drive,-1.0,14.884467

In [5]:
print(len(df))

9704

Question 3. Fuel types (1 point)

In [6]:
fuel_types = df["fuel_type"].unique()
print(fuel_types)
print(len(fuel_types))

['Gasoline' 'Diesel']
2

Question 4. Missing values (1 point)

In [7]:
bool_ar = df.isna().any()
print(bool_ar)

engine_displacement    False
num_cylinders           True
horsepower              True
vehicle_weight         False
acceleration            True
model_year             False
origin                 False
fuel_type              False
drivetrain             False
num_doors               True
fuel_efficiency_mpg    False
dtype: bool

In [8]:
print(df.columns[bool_ar])
len(df.columns[bool_ar])

Index(['num_cylinders', 'horsepower', 'acceleration', 'num_doors'], dtype='object')

4

Question 5. Max fuel efficiency from Asia (1 point)

In [9]:
asia_df = df[df["origin"] == "Asia"]
asia_df

,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,model_year,origin,fuel_type,drivetrain,num_doors,fuel_efficiency_mpg
8,250,1.0,174.0,2714.219310,10.3,2016,Asia,Diesel,Front-wheel drive,-1.0,16.823554
12,320,5.0,145.0,2783.868974,15.1,2010,Asia,Diesel,All-wheel drive,1.0,16.175820
14,200,6.0,160.0,3582.687368,14.9,2007,Asia,Diesel,All-wheel drive,0.0,11.871091
20,150,3.0,197.0,2231.808142,18.7,2011,Asia,Gasoline,Front-wheel drive,1.0,18.889083
21,160,4.0,133.0,2659.431451,NaN,2016,Asia,Gasoline,Front-wheel drive,-1.0,16.077730
...,...,...,...,...,...,...,...,...,...,...,...
9688,260,4.0,NaN,3948.404625,15.5,2018,Asia,Diesel,All-wheel drive,-1.0,11.054830
9692,180,3.0,188.0,3680.341381,18.0,2016,Asia,Gasoline,Front-wheel drive,1.0,11.711653
9693,280,2.0,148.0,2545.070139,15.6,2012,Asia,Diesel,All-wheel drive,0.0,17.202782
9698,180,1.0,131.0,3107.427820,13.2,2005,Asia,Gasoline,Front-wheel drive,-2.0,13.933716
9703,270,3.0,140.0,2908.043477,14.7,2005,Asia,Diesel,All-wheel drive,-1.0,14.884467

In [26]:
print(asia_df.max())
print("\n\n")
print(np.floor(asia_df["fuel_efficiency_mpg"].max() * 100) / 100)

engine_displacement                  370
num_cylinders                       11.0
horsepower                         245.0
vehicle_weight               4661.144932
acceleration                        22.7
model_year                          2023
origin                              Asia
fuel_type                       Gasoline
drivetrain             Front-wheel drive
num_doors                            4.0
fuel_efficiency_mpg            23.759123
dtype: object



23.75

Question 6. Median value of horsepower (1 point)

In [41]:
hrspwr = df["horsepower"]
print(hrspwr)
print(hrspwr.hasnans)

0       159.0
1        97.0
2        78.0
3         NaN
4       140.0
        ...
9699    164.0
9700    154.0
9701    138.0
9702    177.0
9703    140.0
Name: horsepower, Length: 9704, dtype: float64
True

In [30]:
hrspwr_median_with_nan = hrspwr.median()
print(hrspwr_median_with_nan)

149.0

In [32]:
hrspwr_mode = hrspwr.mode()
hrspwr_mode

0    152.0
Name: horsepower, dtype: float64

In [42]:
hrspwr.fillna(hrspwr_mode[0], inplace=True)
print(hrspwr)
print(hrspwr.hasnans)

0       159.0
1        97.0
2        78.0
3       152.0
4       140.0
        ...
9699    164.0
9700    154.0
9701    138.0
9702    177.0
9703    140.0
Name: horsepower, Length: 9704, dtype: float64
False

In [43]:
hrspwr.median()

np.float64(152.0)

Question 7. Sum of weights (1 point)

In [60]:
cars_from_asia = df[df["origin"] == "Asia"]
first_7_cars_from_asia = cars_from_asia[["vehicle_weight", "model_year"]][:7]
print(first_7_cars_from_asia)

    vehicle_weight  model_year
8      2714.219310        2016
12     2783.868974        2010
14     3582.687368        2007
20     2231.808142        2011
21     2659.431451        2016
34     2844.227534        2014
38     3761.994038        2019

In [92]:
X = first_7_cars_from_asia.to_numpy()
print(X.shape)
print(X)

(7, 2)
[[2714.21930965 2016.        ]
 [2783.86897424 2010.        ]
 [3582.68736772 2007.        ]
 [2231.8081416  2011.        ]
 [2659.43145076 2016.        ]
 [2844.22753389 2014.        ]
 [3761.99403819 2019.        ]]

In [94]:
XT = X.T
print(XT.shape)
print(XT)

(2, 7)
[[2714.21930965 2783.86897424 3582.68736772 2231.8081416  2659.43145076
  2844.22753389 3761.99403819]
 [2016.         2010.         2007.         2011.         2016.
  2014.         2019.        ]]

In [103]:
XTX = np.matmul(XT, X)
print(XTX.shape)
print(XTX)

(2, 2)
[[62248334.33150762 41431216.5073268 ]
 [41431216.5073268  28373339.        ]]

In [104]:
inverse_XTX = np.linalg.inv(XTX)
print(inverse_XTX)

[[ 5.71497081e-07 -8.34509443e-07]
 [-8.34509443e-07  1.25380877e-06]]

In [111]:
sanity_check_identity = np.matmul(inverse_XTX, XTX)
print(sanity_check_identity)

[[ 1.00000000e+00  2.13808046e-15]
 [-3.87615815e-15  1.00000000e+00]]

In [106]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])
print(y)

[1100 1300  800  900 1000 1100 1200]

In [108]:
w = np.matmul(np.matmul(inverse_XTX, XT), y)
print(w)

[0.01386421 0.5049067 ]

In [109]:
print(w.sum())

0.5187709081074016